# データソース設定
spring.datasource.url=jdbc:mysql://localhost:3307/shift_manager
spring.datasource.username=hiro
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# サーバー設定
server.port=8080

# Thymeleaf設定
spring.thymeleaf.cache=false

# MyBatis設定
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=io.shiftmanager.you.model
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=io.shiftmanager.you.typehandler

# ログ設定
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG
logging.level.io.shiftmanager.you=DEBUG
logging.level.org.mybatis=DEBUG

